services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf  # Monte le fichier my.cnf
    networks:
      - airflow_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - airflow_network

  airflow:
    build: ./airflow
    image: airflow
    container_name: airflow
    env_file:
      - .env  # Charge toutes les variables d'environnement depuis le fichier .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: >
      bash -c " 
        airflow db init || airflow db upgrade;
        airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com;
        airflow scheduler & airflow webserver
      "
    networks:
      - airflow_network

volumes:
  mysql_data:

networks:
  airflow_network:
